version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.13.3
    env_file:
      - .env
    depends_on:
      - db
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: celery -A server.worker worker -c 1
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    deploy:
      mode: replicated
      replicas: ${WORKER_NUMBER}
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
  enqueue:
    build: .
    profiles:
      - enqueue
    env_file:
      - .env
    depends_on:
      - db
      - worker
      - rabbitmq
    volumes:
      - .:/app

volumes:
  db_data:
