version: "3"

services:
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
