"""create_sensor_table

Revision ID: d919e3244665
Revises: 
Create Date: 2024-06-15 18:11:38.722083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd919e3244665'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1001), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor')),
    schema='public'
    )
    op.create_index(op.f('ix_sensor_name'), 'sensor', ['name'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_name'), table_name='sensor', schema='public')
    op.drop_table('sensor', schema='public')
    # ### end Alembic commands ###
