BEGIN;

CREATE TABLE public.sensor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    CONSTRAINT pk_sensor PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_sensor_name ON public.sensor (name);


CREATE TABLE public.sensor_reading (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    value NUMERIC NOT NULL,
    sensor_id BIGINT,
    CONSTRAINT pk_sensor_reading PRIMARY KEY (id),
    CONSTRAINT fk_sensor_reading_sensor_id FOREIGN KEY(sensor_id) REFERENCES public.sensor (id),
    CONSTRAINT uq_sensor_reading_sensor_id_timestamp UNIQUE (sensor_id, timestamp)
);

CREATE INDEX ix_sensor_reading_sensor_id ON public.sensor_reading (sensor_id);

COMMIT;
